### ISSUE TITLE
NoMethodError: undefined method `compact' for "(cyclic structure)":String

### ISSUE THREAD

**Issue by miks** [route/ferrum#13]
When using together with Cuprite and executing Rspec command like:
`page.evaluate_script("jQuery('body').addClass('not-reloaded');")`
it's erroring with: 
```
NoMethodError: undefined method `compact' for "(cyclic structure)":String
from (pry):5:in `rescue in handle_response'
Caused by NoMethodError: undefined method `compact' for "(cyclic structure)":String
from ~/.rvm/gems/ruby-2.5.3/bundler/gems/ferrum-5b6cb3f617b0/lib/ferrum/page/runtime.rb:127:in `handle_response'
```

Correspoding `reduce_props(object_id, [])`  at https://github.com/route/ferrum/blob/master/lib/ferrum/page/runtime.rb#L122 is returning `"(cyclic structure)"` String, so it's clear why `compact` call is failing.

Not sure what's best approach to handle this case.

**Comment by route** [comment]
Me neither but otherwise you'd get `Stack Level too deep (SystemStackError)` because it is cyclic structure... I checked selenium and this bugs them as well, though I'd prefer returning something meaningful rather then `SystemStackError`.

**Comment by BenoitMC** [comment]
Try to replace `evaluate_script` by `execute_script` if you don't need the return, it solved the problem for me.

**Comment by miks** [comment]
@BenoitMC that did it, thanks!
