### ISSUE TITLE
Brave instead of Chrome?

### ISSUE THREAD

**Issue by hebron-george** [route/ferrum#35]
Is it possible to use [Brave browser](https://brave.com/) instead of Chrome? 

It's supposedly build off of Chromium, if that helps?

Sorry I don't know much so I'm not even sure if this is a valid question to ask.

Thanks!

**Comment by route** [comment]
@hebron-george Sure if it's built on Chrome then it should work. Check out https://github.com/route/ferrum#customization and `Ferrum::Browser.new(browser_path: "/path/to/browser")` option and put a path to your browser bin there. Let me know if it works we can add it to README.

**Comment by hebron-george** [comment]
@route Looks like that worked.

I haven't done any thorough testing though so I'm not sure if there are some features that won't work but at the least - the browser loads up with the page I requested.

Thanks!
