### ISSUE TITLE
Add ability to specify options for browser.goto

### ISSUE THREAD

**Issue by Valve** [route/ferrum#41]
Currently it's not possible to specify options in `browser.goto`, but some options are necessary, for example `wait_until` as in puppeteer

**Comment by dsisnero** [comment]
+1
page.goto(url[, options])
url <string> URL to navigate page to. The url should include scheme, e.g. https://.
options <Object> Navigation parameters which might have the following properties:
timeout <number> Maximum navigation time in milliseconds, defaults to 30 seconds, pass 0 to disable timeout. The default value can be changed by using the page.setDefaultNavigationTimeout(timeout) or page.setDefaultTimeout(timeout) methods.
waitUntil <string|Array<string>> When to consider navigation succeeded, defaults to load. Given an array of event strings, navigation is considered to be successful after all events have been fired. Events can be either:
load - consider navigation to be finished when the load event is fired.
domcontentloaded - consider navigation to be finished when the DOMContentLoaded event is fired.
networkidle0 - consider navigation to be finished when there are no more than 0 network connections for at least 500 ms.
networkidle2 - consider navigation to be finished when there are no more than 2 network connections for at least 500 ms.
referer <string> Referer header value. If provided it will take preference over the referer header value set by page.setExtraHTTPHeaders().
returns: <Promise<?Response>> Promise which resolves to the main resource response. In case of multiple redirects, the navigation will resolve with the response of the last redirect.
page.goto will throw an error if:

there's an SSL error (e.g. in case of self-signed certificates).
target URL is invalid.
the timeout is exceeded during navigation.
the remote server does not respond or is unreachable.
the main resource failed to load.
page.goto will not throw an error when any valid HTTP status code is returned by the remote server, including 404 "Not Found" and 500 "Internal Server Error". The status code for such responses can be retrieved by calling response.status().

NOTE page.goto either throws an error or returns a main resource response. The only exceptions are navigation to about:blank or navigation to the same URL with a different hash, which would succeed and return null.

NOTE Headless mode doesn't support navigation to a PDF document. See the upstream issue.

Shortcut for page.mainFrame().goto(url, options)

**Comment by route** [comment]
In fact it's the major difference between the two. Puppeteer will return control right after it gets response from Chrome that goto command accepted, but Ferrum waits until the page is loaded. If there's JS on the page or some async rendering nothing will help because there's no way to realise that async rendering is done. So if you want to wait that there are no pending network connections I suggest using `network.wait_for_idle`

**Comment by alexanderadam** [comment]
> NOTE Headless mode doesn't support navigation to a PDF document. See the upstream issue.

Can you please point me to the upstream issue?
