### ISSUE TITLE
Use scrollHeight/Width instead of offset for full?

### ISSUE THREAD

**Issue by coffeejunk** [route/ferrum#49]
The `full` option for screenshots is currently using the `offsetHeight` and `offsetWidth`:

https://github.com/route/ferrum/blob/0e96c1cf87ac768df521a6f321ced22f13899b7e/lib/ferrum/page/screenshot.rb#L49-L54

However, on my device™ (in Chrome Version 80.0.3987.116) this returns the size of the viewport. Thus when I run `browser.screenshot(full: true, "google.png")` I get the same result as without the `full: true` option. 

Using the `scrollHeight`/`scrollWidth` instead returns the actual height/width of the rendered site.

PS: thank you for this gem, it has been a joy to use :)

**Comment by route** [comment]
I read about all the heights and widths in one big article. There are even some tests regarding screenshots and the most recent fix was related to full option, did we do a mistake?) if you could write a small test that replicated the issue that would be awesome, see our tests in this repo.

You are welcome!

**Comment by coffeejunk** [comment]
Not a mistake per se, it turns out that `offsetHeight` returns the height of the viewport _if_ the `height` of the `html` element is set to `100%` (the same is true for width). If opened a PR that addresses this.
