### ISSUE TITLE
More screenshot options

### ISSUE THREAD

**Issue by Jakanapes** [route/ferrum#50]
Looking at the source and docs, it seems like the only options for screeshot dimensions are either "full" or "viewport".  

Is there a way to specify the width and height of the viewport?

**Comment by route** [comment]
You can pass window_size when instantiating the browser https://github.com/route/ferrum#customization

If I got your question right

**Comment by Jakanapes** [comment]
Fantastic, that does look like what I want, I just wasn't connecting the two
